version: '3'
services:
  # Traefik service
  reverse-proxy:
    image: traefik:v3.3
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./dynamic.yml:/etc/traefik/dynamic.yml
    networks:
      - traefik-public

  # Web
  redis-1:
    image: redis:latest
    networks:
      - traefik-public
    deploy:
      replicas: 1

  mysql-1:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: motdepasse
      MYSQL_DATABASE: ma_base_de_donnees
    networks:
      - traefik-public
    deploy:
      replicas: 1
    volumes:
      - mysql_gv0:/var/lib/mysql

  get-back-in-touch:
    image: h4lofthemel/get-back-in-touch:v1.0
    networks:
      - traefik-public
    depends_on:
      - mysql-1
      - redis-1
      - reverse-proxy
    environment:
      DB_SERVERNAME: mysql-1
      DB_USERNAME: root
      DB_PASSWORD: motdepasse
      DB_NAME: ma_base_de_donnees
      REDIS_HOST: redis-1
      REDIS_PORT: 6379
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.get-back-in-touch.rule=Host(`utilisateurs.o22408064-2`) || Host(`utilisateurs.localhost`)"
        - "traefik.http.services.get-back-in-touch.loadbalancer.server.port=80"

  # Swarm cluster
  redis-2:
    image: redis:latest
    networks:
      - traefik-public
    deploy:
      replicas: 2
    volumes:
      - redis_data:/data

  mysql-2:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: motdepasse
      MYSQL_DATABASE: ma_base_de_donnees
    networks:
      - traefik-public
    deploy:
      replicas: 1
    volumes:
      - mysql_gv1:/var/lib/mysql

  swarm-cluster:
    image: h4lofthemel/swarm-cluster:v1.0
    networks:
      - traefik-public
    depends_on:
      - mysql-2
      - redis-2
      - reverse-proxy
    environment:
      DB_SERVERNAME: mysql-2
      DB_USERNAME: root
      DB_PASSWORD: motdepasse
      DB_NAME: ma_base_de_donnees
      REDIS_HOST: redis-2
    deploy:
      replicas: 5
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.swarm-cluster.rule=Host(`clusterswarm.o22408064-2`) || Host(`clusterswarm.localhost`)"
        - "traefik.http.services.swarm-cluster.loadbalancer.server.port=80"

  # fortune
  fortune:
    image: h4lofthemel/fortune:v1.0.1
    networks:
      - traefik-public
    depends_on:
      - reverse-proxy
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.fortune.rule=Host(`fortune.o22408064-2`) || Host(`fortune.localhost`)"
        - "traefik.http.services.fortune.loadbalancer.server.port=80"

  # flask
  redis-3:
    image: redis:latest
    networks:
      - traefik-public
    deploy:
      replicas: 1
    volumes:
      - redis_data:/data

  flask:
    image: h4lofthemel/flask:v1.0
    networks:
      - traefik-public
    depends_on:
      - reverse-proxy
      - redis-3
    environment:
      REDIS_HOST: redis-3
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.flask.rule=Host(`flask.o22408064-2`) || Host(`flask.localhost`)"
        - "traefik.http.services.flask.loadbalancer.server.port=80"

  # Web simple
  web-simple:
    image: h4lofthemel/web-simple:v1.0.1
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.apache.rule=PathPrefix(`/web-simple`)"
        - "traefik.http.services.apache.loadbalancer.server.port=80"
        - "traefik.http.routers.apache.middlewares=basicauth"
        - "traefik.http.middlewares.basicauth.basicauth.users=mel:{SHA}qvTGHdzF6KLavt4PO0gs2a6pQ00="
    networks:
      - traefik-public
    depends_on:
      - reverse-proxy

networks:
  traefik-public:
    driver: overlay
    external: false

volumes:
  redis_data:
    driver: local
  mysql_gv0:
    driver: local
    driver_opts:
      type: none
      device: /mnt/gv0
      o: bind
  mysql_gv1:
    driver: local
    driver_opts:
      type: none
      device: /mnt/gv1
      o: bind
      