services:
  # Traefik service
  reverse-proxy:
    image: traefik:v3.3
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
    networks:
      - traefik-public

  # Web
  redis-1:
    image: redis:latest
    networks:
      - get-back-in-touch_default
    deploy:
      replicas: 1

  mysql-1:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: motdepasse
      MYSQL_DATABASE: ma_base_de_donnees
    networks:
      - get-back-in-touch_default
    deploy:
      replicas: 1
    volumes:
      - type: bind
        source: /mnt/gv0
        target: /var/lib/mysql

  get-back-in-touch-1:
    image: h4lofthemel/get-back-in-touch:v1.0
    networks:
      - get-back-in-touch_default
      - traefik-public
    depends_on:
      - mysql-1
      - redis-1
    environment:
      DB_SERVERNAME: mysql-1
      DB_USERNAME: root
      DB_PASSWORD: motdepasse
      DB_NAME: ma_base_de_donnees
      REDIS_HOST: redis-1
      REDIS_PORT: 6379
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.web.rule=Host(`utilisateurs.mel.onthewifi.com`)"
        - "traefik.http.services.web.loadbalancer.server.port=80"

  # Web simple
  web-simple:
    image: h4lofthemel/web-simple:v1.0.1
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.apache.rule=PathPrefix(`/web-simple`)"
        - "traefik.http.services.apache.loadbalancer.server.port=80"
    networks:
      - traefik-public

networks:
  traefik-public:
    driver: overlay
    external: false
  get-back-in-touch_default:
    driver: overlay
    external: false