providers:
  swarm:
    # endpoint: "tcp://127.0.0.1:2375"
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true 
entryPoints:
  web:
    address: ":80"
    http:
      middlewares:
        - global-auth@file
  websecure:
    address: ":443"
    http:
      middlewares:
        - global-auth@file
api:
  insecure: true