version: '3'

services:
  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:v3.3
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS port
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount the configuration file
      - ./traefik.yml:/etc/traefik/traefik.yml
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true