version: '3'

services:
  apache:
    image: h4lofthemel/web-simple
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.apache.rule=PathPrefix(`/web-simple`)"
        - "traefik.http.services.apache.loadbalancer.server.port=80"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true